### ISSUE TITLE
Define mapping from GA registry to corresponding entries in CPU registry

### ISSUE THREAD

**Issue by edburns** [oracle/weblogic-azure#100]
| GA tag name | CPU Tag name |
|--------------|------------------|
| 14.1.1.0-8 |14.1.1.0-generic-jdk8-ol7|
| 14.1.1.0-11 |14.1.1.0-generic-jdk11-ol7| |
| 12.2.1.4 |12.2.1.4-generic-jdk8-ol7 |
| 12.2.1.3 |12.2.1.3-generic-jdk8-ol7 |
| 14.1.1.0-8-ol8 | 14.1.1.0-generic-jdk8-ol8|
| 14.1.1.0-11-ol8 | 14.1.1.0-generic-jdk11-ol8|
| 12.2.1.4-ol8 | 12.2.1.4-generic-jdk8-ol8|
| 12.2.1.3-ol8 |2.2.1.3-generic-jdk8-ol8 |

**Comment by tbarnes-us** [comment]
@mriccell @ddsharpe

**Comment by mriccell** [comment]
provided the CPU image tags corresponding to the GA tags
