### ISSUE TITLE
Additional text in Oracle wlazu Getting Started section

### ISSUE THREAD

**Issue by edburns** [oracle/weblogic-azure#108]
Consider this text from [Get Started with Oracle WebLogic Server on Microsoft Azure IaaS](https://docs.oracle.com/en/middleware/standalone/weblogic-server/wlazu/get-started-oracle-weblogic-server-microsoft-azure-iaas.html#GUID-E0B24A45-F496-4509-858E-103F5EBF67A7):

> The offers described in this document empower you to start your business applications quickly by automatically provisioning the virtual network, storage, and Linux resources, installing Oracle WebLogic Server, setting up security with a network security group, load balancing with Azure Application Gateway, enabling authentication with Azure Active Directory, and easing the Database connectivity.

[Reza](https://github.com/m-reza-rahman/) requests we should also mention support for ELK and Coherence.  Therefore, I suggest the text read as follows instead.

> The offers described in this document empower you to start your business applications quickly by automatically provisioning the virtual network, storage, and Linux resources, installing Oracle WebLogic Server, setting up security with a network security group, load balancing with Azure Application Gateway, enabling authentication with Azure Active Directory, and easing connectivity with databases.  The offers also support HTTP session caching with Oracle Coherence and distributed cloud-scale logging with Elastic Stack.

**Comment by gnsuryan** [comment]
The Oracle WebLogic Server on Microsoft Azure IaaS documentation available at [https://docs.oracle.com/en/middleware/standalone/weblogic-server/wlazu/get-started-oracle-weblogic-server-microsoft-azure-iaas.html#GUID-E0B24A45-F496-4509-858E-103F5EBF67A7](https://docs.oracle.com/en/middleware/standalone/weblogic-server/wlazu/get-started-oracle-weblogic-server-microsoft-azure-iaas.html#GUID-E0B24A45-F496-4509-858E-103F5EBF67A7) has been updated as mentioned in this issue.

Also, all references/links to wls-eng git repository have been changed to point to the oracle/weblogic-azure git repository.
