### ISSUE TITLE
Application gateway can't be accessed after deployment

### ISSUE THREAD

**Issue by majguo** [oracle/weblogic-azure#127]
## Problem description

After a successful deployment of WLS cluster, user can't access Azure Application Gateway deployed along with the cluster:

![image](https://user-images.githubusercontent.com/10357495/161252819-c9ac5cd5-612f-4839-bc97-eca0656a6e79.png)

## How to reproduce

Follow steps below to reproduce the issue:

1. Open [Oracle WebLogic Server Cluster](https://portal.azure.com/#create/oracle.20191007-arm-oraclelinux-wls-cluster20191007-arm-oraclelinux-wls-cluster) offer 
1. In "Basics" page: Fill in value for the required fields. Click "Next".
1. In "TLS/SSL Configuration" page:  Click "Next".
1. In "Azure Application Gateway" page: 
    1. Select "Yes" for "Connect to Azure Application Gateway?"
    1. Select "Generate a self-signed certificate" for "Select desired TLS/SSL certificate option"
    1. Click "Add" under section "User assigned managed identity" > Select a user-assigned managed identity > Click "Add"
1. Click "Review + Create"
1. Click "Create"
1. Wait until the deployment completes successfully.
1. Click "Outputs" of the deployment
1. Copy value of property "appGatewayURL" and open it in the browser. You will see error message "502 Bad Gateway" displayed.

**Comment by galiacheng** [comment]
The issue is caused by a know issue of Application Gateway: https://portal.microsofticm.com/imp/v3/incidents/details/299617853/home

Workaround: configure the backend pool with private IP or internal full hostname.
