### ISSUE TITLE
Oracle WebLogic Server Cluster deployment failed

### ISSUE THREAD

**Issue by majguo** [oracle/weblogic-azure#137]
## Problem description

Failed to deploy Oracle WebLogic Server Cluster from Azure portal, the deployment of embedded template `clusterLinkedTemplate` failed with the following error messages:

```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "VMExtensionProvisioningError",
      "message": "VM has reported a failure when processing extension 'newuserscript'. Error message: \"Enable failed: processing file downloads failed: failed to download file[1]: failed to download file: unexpected status code: actual=404 expected=200\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    },
    {
      "code": "VMExtensionProvisioningError",
      "message": "VM has reported a failure when processing extension 'newuserscript'. Error message: \"Enable failed: processing file downloads failed: failed to download file[1]: failed to download file: unexpected status code: actual=404 expected=200\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
  ]
}
```

## How to reproduce

Follow steps below to reproduce the issue:

1. Open [Oracle WebLogic Server Cluster](https://portal.azure.com/#create/oracle.20191007-arm-oraclelinux-wls-cluster20191007-arm-oraclelinux-wls-cluster) offer.
1. In "Basics" page: Fill in value for the required field(s). Click "Review + Create". Click "Create".
1. Wait until the deployment of embedded template `clusterLinkedTemplate` failed.

## Potential RCA

The `clusterTemplate` will look for some files from `../../../../../utilities/custom-hostname-verifier/`, which seems to depend on the recent changes of parent pom `com.microsoft.azure.iaas:azure-javaee-iaas-parent`:
* https://github.com/oracle/weblogic-azure/blob/main/weblogic-azure-vm/arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster/src/main/arm/nestedtemplates/clusterTemplate.json#L530-L533

Specifically, the dependent parent pom `com.microsoft.azure.iaas:azure-javaee-iaas-parent` has been updated to `1.0.15` in order to add utilities directory from WebLogic offers, see [PR-24](https://github.com/Azure/azure-javaee-iaas/pull/24). However, the old version `1.0.13` and its commit hash `13fe6ec487024eb61355d661ab5700ae90cb0a8f` are **NOT** updated accordingly:
* https://github.com/oracle/weblogic-azure/blob/main/weblogic-azure-vm/arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster/pom.xml#L20
  * Should be updated to `1.0.15`? 
* https://github.com/oracle/weblogic-azure/blob/main/.github/workflows/buildWlsVm4CcArtifact.yml#L23
  * Should be updated to `062fe0eb4e72012ead98c23e1a1b2c6259e7e7c4`? 

It looks like all upstream WebLogic offers that're impacted by the [PR-24](https://github.com/Azure/azure-javaee-iaas/pull/24) should be checked, verified and updated appropriately.

**Comment by sanjaymantoor** [comment]
PR created https://github.com/oracle/weblogic-azure/pull/131 yet to be merged.

**Comment by majguo** [comment]
@edburns PR https://github.com/oracle/weblogic-azure/pull/131 should be merged and released to Partner Center ASAP, since the offer from marketplace or azure portal has already broken.

**Comment by majguo** [comment]
The new release of WLS cluster on Azure including the fix is available. I tested it and all work as expected. Closing the issue now.
