### ISSUE TITLE
Upgrade versions of 3rd party database drivers in VM base images

### ISSUE THREAD

**Issue by edburns** [oracle/weblogic-azure#155]
Most recent available drivers
- PostgreSQL  [42.3.6](https://mvnrepository.com/artifact/org.postgresql/postgresql/42.3.6).
- MSSQL [10.2.1](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/10.2.1.jre8).

Base image offer ids

Oracle tests

- weblogic-122130-jdk8-ol73
- weblogic-122130-jdk8-ol74
- weblogic-122140-jdk8-ol76
- weblogic-122140-jdk8-rhel76

Microsoft tests

- weblogic-141100-jdk11-ol76
- weblogic-141100-jdk11-rhel76
- weblogic-141100-jdk8-ol76
- weblogic-141100-jdk8-rhel76

**Comment by edburns** [comment]
@jacobt123 , I propose that once the base images are available for testing, we split the testing work between Microsoft and Oracle to minimize the time to mitigation.  I suggest Oracle take the first four in the above list and Microsoft the next four.  What do you think?

**Comment by jacobt123** [comment]
@edburns Yes, we'll test the first four once the preview images are available

**Comment by sanjaymantoor** [comment]
Work is in progress. Submitted jobs for creating base VM images.
Following version database drivers were used.

- postgresql-42.3.6.jar
- mssql-jdbc-10.2.1.jre8.jar

**Comment by edburns** [comment]
Testing objectives
Verify the base images all have the correct versions of the jars (see parent issue and related child task)
Do a checksum (UNIX sum(1)) on the jars to verify they are the correct bits as downloaded from maven central.

**Comment by sanjaymantoor** [comment]
Preview images are available 

- [WebLogic 14.1.1.0.0 Base Image on JDK 11/OL 7.6 (preview)](https://portal.azure.com/#create/oracle.weblogic-141100-jdk11-ol76-previewowls-141100-jdk11-ol76)
- [WebLogic Server 14.1.1.0.0 Base Image on JDK8/OL76 (preview)](https://portal.azure.com/#create/oracle.weblogic-141100-jdk8-ol76-previewowls-141100-jdk8-ol76)
- [WebLogic 12.2.1.4.0 Base Image and JDK 8 on OL 7.6 (preview)](https://portal.azure.com/#create/oracle.weblogic-122140-jdk8-ol76-previewowls-122140-jdk8-ol76)
- [WebLogic 12.2.1.3.0 Base Image and JDK 8 on OL 7.4 (preview)](https://portal.azure.com/#create/oracle.weblogic-122130-jdk8-ol74-previewowls-122130-jdk8-ol74)
- [WebLogic 12.2.1.3.0 Base Image and JDK 8 on OL 7.3 (preview)](https://portal.azure.com/#create/oracle.weblogic-122130-jdk8-ol73-previewowls-122130-jdk8-ol73)
- [WebLogic 14.1.1.0.0 Base Image on JDK 11/RHEL 7.6 (preview)](https://portal.azure.com/#create/oracle.weblogic-141100-jdk11-rhel76-previewowls-141100-jdk11-rhel76)
- [WebLogic 14.1.1.0.0 Base Image on JDK 8/RHEL 7.6 (preview)](https://portal.azure.com/#create/oracle.weblogic-141100-jdk8-rhel76-previewowls-141100-jdk8-rhel76)
- [WebLogic 12.2.1.4.0 Base Image on JDK 8/RHEL 7.6 (preview)](https://portal.azure.com/#create/oracle.weblogic-122140-jdk8-rhel76-previewowls-122140-jdk8-rhel76)

**Comment by sanjaymantoor** [comment]
Submitted for admin, cluster and dynamic cluster offer changes to publish at marketplace.

**Comment by sanjaymantoor** [comment]
Admin,cluster and dynamic cluster offer preview images are available at marketplace.

**Comment by sanjaymantoor** [comment]
Azure application offers admin,cluster and dynamic cluster are made live at marketplace.
Azure virtual machine images are also made live at marketplace
