### ISSUE TITLE
Create plan for closing down wls-eng repos

### ISSUE THREAD

**Issue by edburns** [oracle/weblogic-azure#17]
- gh-pages
   - make it so microsoft docs that point to old repo are pointing to new repo instead
- issue tracker
   - move over appropriate issues from old repo to this one
- CI/CD
  - Ensure @jacobt123  has access to create and update secrets for use in GitHub Actions

**Comment by edburns** [comment]
See [help with zip generation](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1428896)

**Comment by jacobt123** [comment]
@edburns I don't have access to that link
