### ISSUE TITLE
Publish new version WLS on AKS offer with "BYOV"

### ISSUE THREAD

**Issue by galiacheng** [oracle/weblogic-azure#170]
**Offer**: [WLS on AKS offer ](https://partner.microsoft.com/en-us/dashboard/commercial-marketplace/offers/a1775ed4-512c-4cfa-9e68-f0b09b36de90/overview)
**Package file (.zip)**: download the artifact from this [pipeline](https://github.com/galiacheng/weblogic-azure/actions/runs/2546306244), or click [wls-on-aks-azure-marketplace-1.0.38-arm-assembly](https://github.com/galiacheng/weblogic-azure/suites/7053070687/artifacts/277903473)

More details of testing:

- [Successful pipeline](https://github.com/galiacheng/weblogic-azure/actions/runs/2546213778)
- [Test offer](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20210525-arm-oraclelinux-wls-on-aks-preview20210525-arm-oraclelinux-wls-on-aks)
- Successful deployment of test offer- 
![image](https://user-images.githubusercontent.com/59823457/175228783-7d979c92-40d6-41d6-960b-6a941b131ba1.png)

**Comment by sanjaymantoor** [comment]
I have uploaded wls-on-aks-azure-marketplace-1.0.38-arm-assembly.zip and published the changes.
Currently “Oracle WebLogic Server on Azure Kubernetes Service | Offer” is in progress.

**Comment by sanjaymantoor** [comment]
Oracle WebLogic Server on Azure Kubernetes Service preview is available at marketplace.
Let me know whether I need to go ahead with publish Live.

**Comment by galiacheng** [comment]
Validate preview offer:
![image](https://user-images.githubusercontent.com/59823457/175252872-c0d6bbb6-eb48-4d25-b755-6d3762b4f543.png)

It's ready to go live.

**Comment by sanjaymantoor** [comment]
I have made Go Live and currently offer is under certification section.

**Comment by galiacheng** [comment]
Hello @sanjaymantoor there is certificate issue #171 , pr #172  is to workaround it, I have build the fix in [this pipeline](https://github.com/galiacheng/weblogic-azure/actions/runs/2553311685), could you upload [wls-on-aks-azure-marketplace-1.0.39-arm-assembly](https://github.com/galiacheng/weblogic-azure/suites/7072016283/artifacts/279102017)?

**Comment by sanjaymantoor** [comment]
I have uploaded wls-on-aks-azure-marketplace-1.0.39-arm-assembly.zip and published the changes.
Currently “Oracle WebLogic Server on Azure Kubernetes Service | Offer” is in progress.

**Comment by sanjaymantoor** [comment]
Oracle WebLogic Server on Azure Kubernetes Service is in preview state and available for testing.

**Comment by galiacheng** [comment]
Validate preview offer done.

![image](https://user-images.githubusercontent.com/59823457/175477717-6e60a788-e8f8-452f-95a7-1d15b9b5707d.png)

Ready to go live.

**Comment by sanjaymantoor** [comment]
Oracle WebLogic Server on Azure Kubernetes Service is submitted to Go Live.

**Comment by galiacheng** [comment]
The offer is live, close this issue.
