### ISSUE TITLE
WLS on AKS: Typo error in createUIDefinition under aksSupportedVersionTextBlock section

### ISSUE THREAD

**Issue by gnsuryan** [oracle/weblogic-azure#193]
WLS on AKS: Typo error in createUIDefinition under aksSupportedVersionTextBlock section
The help text has the word "the" repeated wrongly.
,
                            {
                                "name": "aksSupportedVersionTextBlock",
                                "type": "Microsoft.Common.TextBlock",
                                "visible": "[bool(steps('section_aks').clusterInfo.createAKSCluster)]",
                                "options": {
                                    "icon": "Info",
                                    "text": "AKS supports a range of Kubernetes versions.  This offer is tested with a specific Kubernetes version known to work with WebLogic Server on AKS; click 'Learn more' **to the find the** version information.",
                                    "link": {
                                        "label": "Learn more",
                                        "uri": "https://aka.ms/wls-aks-well-tested-version"
                                    }
                                }
                            }

**Comment by gnsuryan** [comment]
Type error is found in the following file: 

https://raw.githubusercontent.com/oracle/weblogic-azure/main/weblogic-azure-aks/src/main/arm/createUiDefinition.json

**Comment by galiacheng** [comment]
Thanks for the issue @gnsuryan I will create a PR to fix is ASAP.
