### ISSUE TITLE
Upgrade PostgreSQL driver in vm base images

### ISSUE THREAD

**Issue by galiacheng** [oracle/weblogic-azure#227]
Older version has vulnerabilities, please upgrade to https://mvnrepository.com/artifact/org.postgresql/postgresql/42.5.1.

**Comment by sanjaymantoor** [comment]
WebLogic on Azure base vm images are published for Oracle Linux and RHEL. WebLogic on Azure offers with PostgreSQL driver version updated to 42.5.1 are available at marketplace.
