### ISSUE TITLE
Remove AAD description from oracle doc

### ISSUE THREAD

**Issue by galiacheng** [oracle/weblogic-azure#244]
Per PM requires, we will remove AAD from all the VM offers. #243 is to remove AAD from UI.

This issue is to remove related description from the [oracle doc](https://docs.oracle.com/en/middleware/standalone/weblogic-server/wlazu/deploy-oracle-weblogic-server-single-node-microsoft-azure-iaas.html#GUID-C28B2CBE-1A3B-4EC5-8622-31D53029640D).

- For admin offer
  
![image](https://user-images.githubusercontent.com/59823457/219256437-227c7b6d-e5d0-4109-a1ac-b6c588c749b0.png)
![image](https://user-images.githubusercontent.com/59823457/219256775-8f671139-da76-4440-a4ed-b0a629a9003c.png)

- For cluster offer (same location with admin offer)
- For dynamic offer (same location with admin offer)
- About Deploying Oracle WebLogic Server on Microsoft Azure IaaS
  
![image](https://user-images.githubusercontent.com/59823457/218068717-cdf6d752-4976-4dd9-ac26-79f6155993a4.png)

**Comment by sanjaymantoor** [comment]
Oracle document is refreshed with requested changes. Refer [oracle doc](https://docs.oracle.com/en/middleware/standalone/weblogic-server/wlazu/deploy-oracle-weblogic-server-single-node-microsoft-azure-iaas.html#GUID-C28B2CBE-1A3B-4EC5-8622-31D53029640D).
