### ISSUE TITLE
Remove ELK description from oracle doc

### ISSUE THREAD

**Issue by galiacheng** [oracle/weblogic-azure#250]
Per PM requires, we will remove ELK from all the VM offers. #249 is to remove ELK from UI.

This issue is to remove related description from the [oracle doc](https://docs.oracle.com/en/middleware/standalone/weblogic-server/wlazu/deploy-oracle-weblogic-server-single-node-microsoft-azure-iaas.html#GUID-C28B2CBE-1A3B-4EC5-8622-31D53029640D).

- For admin offer
  
![image](https://user-images.githubusercontent.com/59823457/221740919-75d2138b-0628-43a7-b473-c59e5eb17753.png)
![image](https://user-images.githubusercontent.com/59823457/221741193-313d37b8-9db9-4fad-9e25-cbb37ee40d78.png)

- For cluster offer (same location with admin offer)
- For dynamic offer (same location with admin offer)
- About Deploying Oracle WebLogic Server on Microsoft Azure IaaS
  
![image](https://user-images.githubusercontent.com/59823457/221741350-74fff939-be88-4650-bce6-3b5d0a97dd82.png)

**Comment by edburns** [comment]
Confirmed. This can be closed.
