### ISSUE TITLE
Make it so "Terms of use" for all offers in Partner Center is plain text, not HTML

### ISSUE THREAD

**Issue by edburns** [oracle/weblogic-azure#29]
When a user deploys one of our offers from the Azure Marketplace, they are presented with a link to review the terms of use, as shown here.

![image](https://user-images.githubusercontent.com/75821/135904962-a0e1a84d-47e8-4c19-8c97-6da2eb563625.png)

Here is an example of [such a link](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWCwpv). Clicking this link shows the text provided in the **Terms and conditions text** in the Partner Center, as shown here.

![image](https://user-images.githubusercontent.com/75821/135905231-50321961-de8f-453f-9b52-05ee7eab4f43.png)

As you can see, this text should not be HTML.

To fix this issue, the assignee must go through each of the following offers in Partner Center and remove the HTML from the **Terms and conditions text** field and re-publish the offers.

Offer ids
* 20191001-arm-oraclelinux-wls
* 20191007-arm-oraclelinux-wls-cluster
* 20191009-arm-oraclelinux-wls-admin
* 20210620-wls-on-aks
* 20191021-arm-oraclelinux-wls-dynamic-cluster
* oraclelinux-wls-cluster

**Comment by sanjaymantoor** [comment]
I verified following offers and found "Terms of user" are in plain text.

- WebLogic Server 12.2.1.4.0 and JDK8 on RHEL7.6WebLogic Server 14.1.1.0.0 Base Image and JDK11 on RHEL7.6
- WebLogic Server 14.1.1.0.0 Base Image and JDK8 on RHEL7.6
- WebLogic Server 14.1.1.0.0 Base Image and JDK8 on RHEL7.6 (weblogic-141100-jdk8u251-ol76)
- WebLogic Server 12.2.1.4.0 Base Image with JDK8 on Oracle Linux 7.6
- Oracle HTTP Server 12.2.1.4.0 and JDK8 on Oracle Linux 7.3
- Oracle HTTP Server 12.2.1.4.0 and JDK8 on Oracle Linux 7.4
- Oracle HTTP Server 12.2.1.4.0 and JDK8 on Oracle Linux 7.6
- WebLogic 12.2.1.3.0 Base Image JDK8 on OL7.4 (weblogic-122130-jdk8-ol74)
- WebLogic Server 12.2.1.3.0 Base Image and JDK8 on Oracle Linux 7.3(weblogic-122130-jdk8-ol73)
- WebLogic Server 14.1.1.0.0 Base Image and JDK11 on Oracle Linux 7.6 ( weblogic-141100-jdk11-ol76 )
- WebLogic Server 14.1.1.0.0 Base Image and JDK8 on Oracle Linux 7.6 (weblogic-141100-jdk8-ol76)
